export const dataCarInputs = {
  weight: "3800",
  front_percent: "50",
  front_arb: "17",
  rear_arb: "17",
  front_aero: "0",
  power_hp: "290",
  hp_per_ton: "0",
};

export const dataCarOutputs = {
  front_camber_results: "2.0",
  front_camber_fine_tune_results: "2.0",
  rear_camber_results: "1.6",
  rear_camber_fine_tune_results: "1.6",
  front_toe_results: "0.0",
  front_toe_fine_tune_results: "0.0",
  rear_toe_results: "0.0",
  rear_toe_fine_tune_results: "0.0",
  front_arb_results: "0.0",
  front_arb_fine_tune_results: "0.0",
  rear_arb_results: "0.0",
  rear_arb_fine_tune_results: "0.0",
  front_springs_results: "0.0",
  front_springs_fine_tune_results: "0.0",
  rear_springs_results: "0.0",
  rear_springs_fine_tune_results: "0.0",
  front_rebound_results: "0.0",
  front_rebound_fine_tune_results: "0.0",
  rear_rebound_results: "0.0",
  rear_rebound_fine_tune_results: "0.0",
  front_bump_results: "0.0",
  front_bump_fine_tune_results: "0.0",
  rear_bump_results: "0.0",
  rear_bump_fine_tune_results: "0.0",
  front_aero_results: "0.0",
  front_aero_fine_tune_results: "0.0",
  rear_aero_results: "0.0",
  rear_aero_fine_tune_results: "0.0",
  front_caster_results: "6.0",
  front_caster_fine_tune_results: "6.0",
};
